"""
Synthesizer Agent for PolicyLens.

Takes a user query and retrieved passages from the RetrieverAgent,
then uses the LLM provider chain to generate a cited answer.

The prompt engineering is critical here: it instructs the LLM to
ground its answer ONLY in the provided passages and to cite sources
using [Source: filename, p.X] format. This reduces hallucination
and makes answers verifiable.
"""

from src.core.base_agent import BaseAgent
from src.core.llm_provider import llm_chain


class SynthesizerAgent(BaseAgent):
    """Generates cited answers from retrieved passages using LLM.

    Constructs a grounded prompt that forces the LLM to use only
    the provided context, cite sources explicitly, and acknowledge
    when information is insufficient. The answer quality depends
    heavily on retrieval quality — garbage in, garbage out.
    """

    def __init__(self, name: str = "synthesizer", description: str = ""):
        super().__init__(name=name, description=description)

    def process(self, input_data: dict) -> dict:
        """Generate a cited answer from query and retrieved passages.

        Args:
            input_data: Must contain 'query' (str) and 'passages' (list).
                        Optional: 'max_tokens', 'temperature'.

        Returns:
            Dictionary with answer, citations, provider info, and confidence.
        """
        query = input_data["query"]
        passages = input_data.get("passages", [])
        max_tokens = input_data.get("max_tokens", 2048)
        temperature = input_data.get("temperature", 0.3)

        if not passages:
            self.logger.warning("No passages provided for query: %s", query[:80])
            return {
                "query": query,
                "answer": "I could not find relevant information to answer this question.",
                "citations": [],
                "llm_provider": "",
                "confidence": 0.0,
            }

        # Build the grounded prompt
        prompt = self._build_prompt(query, passages)

        self.logger.info(
            "Generating answer for: '%s' using %d passages",
            query[:80],
            len(passages),
        )

        # Generate answer using LLM chain (auto-failover)
        llm_response = llm_chain.generate(
            prompt=prompt,
            max_tokens=max_tokens,
            temperature=temperature,
        )

        # Extract citations from passages used
        citations = self._build_citations(passages)

        # Estimate confidence based on retrieval scores
        confidence = self._estimate_confidence(passages)

        self.logger.info(
            "Answer generated by %s in %.2fs (%d tokens)",
            llm_response.provider,
            llm_response.latency,
            llm_response.tokens_used,
        )

        return {
            "query": query,
            "answer": llm_response.text,
            "citations": citations,
            "llm_provider": llm_response.provider,
            "llm_model": llm_response.model,
            "llm_latency": llm_response.latency,
            "tokens_used": llm_response.tokens_used,
            "confidence": confidence,
            "passages_used": len(passages),
        }

    def _build_prompt(self, query: str, passages: list[dict]) -> str:
        """Construct a grounded prompt that forces cited answers.

        The prompt structure is carefully designed to:
        1. Set the role (policy analyst)
        2. Provide the context passages with source labels
        3. Give explicit instructions about citation format
        4. Ask the question

        Args:
            query: User's question.
            passages: Retrieved passages with metadata.

        Returns:
            Complete prompt string for the LLM.
        """
        # Format each passage with a source label
        context_parts = []
        for i, passage in enumerate(passages, 1):
            source_file = passage.get("source_file", "Unknown")
            page = passage.get("page_number", 0)
            score = passage.get("score", 0)
            content = passage.get("content", "")

            context_parts.append(
                f"[Source {i}: {source_file}, p.{page}] (relevance: {score:.2f})\n"
                f"{content}"
            )

        context_block = "\n\n---\n\n".join(context_parts)

        prompt = f"""You are a policy analyst answering questions based strictly on the provided source documents. Your answer must be grounded in the given context only.

CONTEXT PASSAGES:
{context_block}

INSTRUCTIONS:
- Answer the question based ONLY on the context passages above.
- Cite your sources using the format [Source: filename, p.X] after each claim.
- If the context does not contain enough information, say so explicitly.
- Be specific and use data, numbers, and direct references where available.
- Structure your answer clearly with key points.
- Do not make claims that are not supported by the provided passages.

QUESTION: {query}

ANSWER:"""

        return prompt

    def _build_citations(self, passages: list[dict]) -> list[dict]:
        """Build structured citations from the passages used.

        Args:
            passages: Retrieved passages with metadata.

        Returns:
            List of citation dicts with source file, page, and relevance.
        """
        citations = []
        seen_sources = set()

        for passage in passages:
            source_file = passage.get("source_file", "")
            page = passage.get("page_number", 0)
            key = f"{source_file}_p{page}"

            if key not in seen_sources:
                seen_sources.add(key)
                citations.append({
                    "source_file": source_file,
                    "page_number": page,
                    "chunk_id": passage.get("chunk_id", ""),
                    "relevance_score": passage.get("score", 0.0),
                })

        return citations

    def _estimate_confidence(self, passages: list[dict]) -> float:
        """Estimate answer confidence from retrieval scores.

        Higher retrieval scores mean the passages are more relevant,
        which generally means the answer is more likely to be correct.
        This is a heuristic, not a guarantee — the VerifierAgent
        provides actual factual verification later.

        Args:
            passages: Retrieved passages with scores.

        Returns:
            Confidence score between 0 and 1.
        """
        if not passages:
            return 0.0

        scores = [p.get("score", 0) for p in passages]
        avg_score = sum(scores) / len(scores)
        top_score = max(scores)

        # Weighted combination: top score matters more than average
        confidence = 0.6 * top_score + 0.4 * avg_score
        return round(min(confidence, 1.0), 4)